hostname r1
!
router bgp 65001
 bgp router-id 1.1.1.1
 
 ! --- Bloco Dinamico de Vizinhos ---
 
 neighbor 10.0.0.2 remote-as 65002
 
 neighbor 10.0.0.3 remote-as 65003
 
 neighbor 10.0.0.4 remote-as 65004
 
 ! ----------------------------------
 
 network 192.168.1.0/24
!
end