hostname r2
!
router bgp 65002
 bgp router-id 2.2.2.2
 
 ! --- Bloco Dinamico de Vizinhos ---
 
 neighbor 10.0.0.1 remote-as 65001
 
 ! ----------------------------------
 
 network 192.168.2.0/24
!
end