hostname r3
!
router bgp 65003
 bgp router-id 3.3.3.3
 
 ! --- Bloco Dinamico de Vizinhos ---
 
 neighbor 10.0.0.1 remote-as 65001
 
 ! ----------------------------------
 
 network 192.168.3.0/24
!
end