hostname r4
!
router bgp 65004
 bgp router-id 4.4.4.4
 
 ! --- Bloco Dinamico de Vizinhos ---
 
 neighbor 10.0.0.1 remote-as 65001
 
 ! ----------------------------------
 
 network 192.168.4.0/24
!
end